# Makefile de l'ex 26
# Franck.Quessette@uvsq.fr
# Novembre 2016
#$(CFLAGS) -o xecutable

CFLAGS=-c -g -Wall


all: ex26
	./a.out

ex26: ex26.c
	gcc ex26.c fichier_test 


clean:
	rm a.out
	rm -f xecutable
	rm -f *.o
